---
# version to setup of origin
## Note: originally we added the v to the version, but for consistency this should be the exact version
## ex. 3.10.0-alpha.0 becomes v3.10.0-alpha.0
## This code commented and can be reused if the exact version doesn't matter
#- name: set latest tag from git tag
#  shell: "git tag --list '{{ project }}-{{ version }}.*' | sort -V |sed \"s/{{ project }}-{{ version }}.//\" | tail -n1"
#  args:
#    chdir: "{{ openshift_repo_path }}"
#  register: LATEST_TAG
# To find this out:
# git ls-remote --tags https://github.com/openshift/openshift-ansible \
# | egrep 'openshift-ansible-[0-9]' | sort -t '/' -k 3 -V | tail -1 | awk '{print $2}' \
# | sed 's/refs\/tags\/\(.*\)/\1/' | sed 's/\^{}//'

- debug:
    msg: "PaaS-sig Props: {{ item.prop }} [ {{ item.value }} ]"
  with_items:
    - { prop: 'project', value: "{{ project }}" }
    - { prop: 'oa_version', value: "{{ oa_version }}" }
    - { prop: 'bleeding_edge', value: "{{ bleeding_edge }}" }
    #- { prop: 'latest_tag', value: "{{ LATEST_TAG.stdout }}" }

- block:
    - name: "Checkout openshift-ansible version - {{ oa_version }}"
      #shell: "git checkout {{ project }}-{{ oa_version }}.{{ LATEST_TAG.stdout }}"
      command: git checkout {{ oa_version }}
      args:
        chdir: "{{ openshift_repo_path }}"
  when:
    - not ( bleeding_edge | bool )
